service: pluto-redirector

provider:
  name: aws
  runtime: nodejs6.10
  stage: stage
  region: us-east-1

functions:
  redirect:
    handler: handler.redirect
    events:
      - http:
          method: get
          path: ${self:service}
      - http:
          method: any
          path: "${self:service}/{proxy+}"

resources:
  Resources:
    RedirectLogGroup:
      Properties:
        RetentionInDays: "1"
